config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :disco_pedidos
    resources :pedidos
    resources :canciones
    resources :discos
    resources :artistas
    get "", to: "home#index"
    get 'home/index'
    get 'sesiones/new'
    post 'sesiones/create'
    get 'sesiones/destroy'
    resources :clientes
  end
  get 'carrito', to: "carritos#show", as: "carrito"
  get 'carrito/agregar/:disco_id', to: "carritos#agregar", as: "carrito_agregar"
  get 'carrito/quitar/:disco_id', to: "carritos#quitar", as: "carrito_quitar"
  get 'carrito/menos/:disco_id', to: "carritos#menos", as: "carrito_menos"
  get 'carrito/mas/:disco_id', to: "carritos#mas", as: "carrito_mas"
  get 'carrito/vaciar', to: "carritos#vaciar", as: "carrito_vaciar"
  get "contactanos", to: "home#contactanos"
  get "faq", to: "home#faq"
  get "sobre", to: "home#sobre"
  get "perfil", to: "clientes#perfil"
  get 'sesion', to: "sesiones#new"
  post 'sesion', to: "sesiones#create"
  delete 'sesion', to: "sesiones#destroy"
  get 'home/index'
  get 'home', to: "home#index"
  get 'registro', to: "registros#new"
  post 'registro', to: "registros#create"
  root "home#index"
  get "artistas/buscar"
  get "discos/buscar"
  resources :pedidos, only: %i[ index show new create ]
  resources :canciones, only: %i[ index show ]
  resources :discos, only: %i[ index show ]
  resources :artistas,  only: %i[ index show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/pedido.rb
class Pedido < ApplicationRecord
###
### Associations
###
  belongs_to :cliente
  has_many :disco_pedidos
###
### Validations
###
  validates :codigo, format: {with: /[0-9A-Z]{12}/}
  validates :destino, presence: true

###
### Scopes
###
  def total
    disco_pedidos.reduce(0) { |sum, disco_pedido| sum += disco_pedido.disco.precio }
  end
end

app/controllers/admin/pedidos_controller.rb
class Admin::PedidosController < ApplicationController
  before_action :set_pedido, only: %i[ show edit update destroy ]
  before_action :requiere_ser_admin
  # GET /admin/pedidos or /admin/pedidos.json
  def index
    @pagy, @pedidos = pagy(Pedido.all)
  end

  # GET /admin/pedidos/1 or /admin/pedidos/1.json
  def show
  end

  # GET /admin/pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /admin/pedidos/1/edit
  def edit
  end

  # POST /admin/pedidos or /admin/pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to admin_pedido_url(@pedido), notice: "Pedido was successfully created." }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/pedidos/1 or /admin/pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to admin_pedido_url(@pedido), notice: "Pedido was successfully updated." }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/pedidos/1 or /admin/pedidos/1.json
  def destroy
    @pedido.disco_pedidos.destroy_all
    @pedido.destroy

    respond_to do |format|
      format.html { redirect_to admin_pedidos_url, notice: "Pedido was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_params
      params.require(:pedido).permit(:cliente_id, :destino, :codigo)
    end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: %i[ show edit update destroy ]
  before_action :requiere_sesion
  before_action :carga_carrito, only: %i[ new create ]
  before_action :carrito_no_vacio, only: %i[ new create ]
  after_action :guarda_carrito, only: %i[ create ]

  # GET /pedidos or /pedidos.json
  def index
    @pagy, @pedidos = pagy(@cliente.pedidos)
  end

  # GET /pedidos/1 or /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    if @carrito.empty?
      redirect_to root_url
    end
    @pedido = Pedido.new
  end

  # POST /pedidos or /pedidos.json
  def create
    ActiveRecord::Base.transaction do
      @pedido = Pedido.create!(codigo: genera_codigo, destino: params[:destino], cliente: @cliente)
      @carrito.each do |disco, cantidad|
        DiscoPedido.create(pedido: @pedido, disco: disco, cantidad: cantidad)
      end
    rescue ActiveRecord::RecordInvalid
      flash[:alert] = "El pedido no se pudo completar"
        redirect_to new_pedido_url
    end
    @carrito.quitar_todos
    flash[:notice] = "El pedido se completó con éxito"
    redirect_to pedido_url(@pedido)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = @cliente.pedidos.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_params
      params.require(:pedido).permit(:destino)
    end

    def requiere_sesion_iniciada
      if @cliente.nil?
        redirect_to sesion_url
      end
    end

    def genera_codigo
      SecureRandom.alphanumeric(12).upcase
    end

    def nuevo_codigo
      while true
        codigo = genera_codigo
        if Pedido.find_by(codigo: codigo)
          return codigo
        end
      end
    end

    def carrito_no_vacio
      if @carrito.empty?
        redirect_to root_url
      end
    end
end

app/helpers/admin/pedidos_helper.rb
module Admin::PedidosHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/admin/pedidos/_form.html.erb
<%= form_with(model: [:admin, pedido]) do |form| %>
  <% if pedido.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
        <% pedido.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-2">
    <%= form.label :codigo %>
    <%= form.text_field :codigo %>
  </div>
  <div class="mt-2">
    <%= form.label :cliente_id %>
    <%= form.text_field :cliente_id %>
  </div>
   <div class="mt-2">
    <%= form.label :destino %>
    <%= form.text_field :destino %>
  </div>
  <div>
    <%= form.submit class: "btn btn-success mt-2" %>
  </div>
<% end %>

app/views/admin/pedidos/_pedido.html.erb
    <p>Id: <%= pedido.id %></p>
    <p>Código: <%= pedido.codigo %></p>
    <p>Cliente: <%= pedido.cliente.nombre %></p>
    <p>Destino: <%= pedido.destino %></p>

app/views/admin/pedidos/edit.html.erb
<h1 class="text-center m-3">Editar pedido</h1>

<div class="container">
<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Muestra este pedido", [:admin, @pedido] %> |
  <%= link_to "Vuelve a lista de pedidos", admin_pedidos_path %>
</div>
</div>

app/views/admin/pedidos/index.html.erb
<h1 class="text-center p-3">Pedidos</h1>



<div class="container" id="pedidos">
<%= link_to "Nuevo pedido", new_admin_pedido_path, class: "d-block mb-4" %>
  <% @pedidos.each do |pedido| %>
    <a href="<%= admin_pedido_path(pedido) %>" class="d-flex gap-2 align-items-center text-decoration-none text-secondary border border-1 rounded rounded-2 mb-2 p-2">
      <%= render pedido %>
    </a>
  <% end %>
</div>

<div class="d-flex mt-4 m-auto justify-content-center">
<%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/admin/pedidos/new.html.erb
<h1 class="text-center m-3">Nuevo pedido</h1>

<div class="container">
<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Volver a lista de pedidos", admin_pedidos_path %>
</div>
</div>

app/views/admin/pedidos/show.html.erb
<div class="container m-5 p-3">
  <%= render @pedido %>
  <div>
  <%= link_to "Edita este pedido", edit_admin_pedido_path(@pedido) %> |
  <%= link_to "Volver a lista de pedidos", admin_pedidos_path %>

  <%= button_to "Borrar este pedido", [:admin, @pedido], method: :delete, class: "mt-2 btn btn-danger" %>
</div>
</div>