config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :disco_pedidos
    resources :pedidos
    resources :canciones
    resources :discos
    resources :artistas
    get "", to: "home#index"
    get 'home/index'
    get 'sesiones/new'
    post 'sesiones/create'
    get 'sesiones/destroy'
    resources :clientes
  end
  get 'carrito', to: "carritos#show", as: "carrito"
  get 'carrito/agregar/:disco_id', to: "carritos#agregar", as: "carrito_agregar"
  get 'carrito/quitar/:disco_id', to: "carritos#quitar", as: "carrito_quitar"
  get 'carrito/menos/:disco_id', to: "carritos#menos", as: "carrito_menos"
  get 'carrito/mas/:disco_id', to: "carritos#mas", as: "carrito_mas"
  get 'carrito/vaciar', to: "carritos#vaciar", as: "carrito_vaciar"
  get "contactanos", to: "home#contactanos"
  get "faq", to: "home#faq"
  get "sobre", to: "home#sobre"
  get "perfil", to: "clientes#perfil"
  get 'sesion', to: "sesiones#new"
  post 'sesion', to: "sesiones#create"
  delete 'sesion', to: "sesiones#destroy"
  get 'home/index'
  get 'home', to: "home#index"
  get 'registro', to: "registros#new"
  post 'registro', to: "registros#create"
  root "home#index"
  get "artistas/buscar"
  get "discos/buscar"
  resources :pedidos, only: %i[ index show new create ]
  resources :canciones, only: %i[ index show ]
  resources :discos, only: %i[ index show ]
  resources :artistas,  only: %i[ index show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cliente.rb
class Cliente < ApplicationRecord

    REQUERIMIENTOS_PASSWORD = /\A
        (?=.{8,})
        (?=.*\d)
        (?=.*[a-z])
        (?=.*[A-Z])
        (?=.*[[:^alnum:]])
    /x
###
### Associations
###
    has_many :pedidos
###
### Validations
###
    validates :nombre, format: {with: /[a-zA-Z]+ [a-zA-Z]+/, message: "debe tener al menos dos palabras de más de una letra cada una"}
    validates :email, format: {with: URI::MailTo::EMAIL_REGEXP, message: "tiene un formato incorrecto"}, uniqueness: { message: "ya está en uso"}
    validates :password, format: {with: REQUERIMIENTOS_PASSWORD, message: "no cumple los requerimientos"}
    validates_confirmation_of :password, allow_blank: true, message: " no coincide con la contraseña"
###
### Autenticacion
###
    has_secure_password validations: false

    
end

app/controllers/admin/clientes_controller.rb
class Admin::ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]
  before_action :requiere_ser_admin
  # GET /admin/clientes or /admin/clientes.json
  def index
    @pagy, @clientes = pagy(Cliente.all)
  end

  # GET /admin/clientes/1 or /admin/clientes/1.json
  def show
  end

  # GET /admin/clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /admin/clientes/1/edit
  def edit
  end

  # POST /admin/clientes or /admin/clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to admin_cliente_url(@cliente), notice: "Cliente was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/clientes/1 or /admin/clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to admin_cliente_url(@cliente), notice: "Cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/clientes/1 or /admin/clientes/1.json
  def destroy
    @cliente.pedidos.each do |pedido|
      pedido.disco_pedidos.destroy_all
      pedido.destroy
    end
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to admin_clientes_url, notice: "Cliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:password, :email, :nombre)
    end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  #before_action :set_cliente, only: %i[ show edit update destroy ]

  before_action :requiere_sesion, only: %i[perfil]

  # GET /perfil
  def perfil
    render "show"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:clienteid])
    end

end

app/helpers/admin/clientes_helper.rb
module Admin::ClientesHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
    def digest_password(password, salt)
        return salt + Digest::SHA256.hexdigest(password + salt)
    end

    def validate_password(password, password_digest)
        return digest_password(password, password_digest[0,8]) == password_digest
    end
end

app/views/admin/clientes/_cliente.html.erb
    <p>Id: <%= cliente.id %></p>
    <p>Nombre: <%= cliente.nombre %></p>
    <p>Email: <%= cliente.email %></p>

app/views/admin/clientes/_form.html.erb
<%= form_with(model: [:admin, cliente]) do |form| %>
  <% if cliente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mt-2">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>
   <div class="mt-2">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
   <div class="mt-2">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit class: "btn btn-success mt-2" %>
  </div>
<% end %>

app/views/admin/clientes/edit.html.erb
<h1 class="text-center m-3">Editar cliente</h1>

<div class="container">
<%= render "form", cliente: @cliente %>

<br>

<div>
  <%= link_to "Muestra este cliente", [:admin, @cliente] %> |
  <%= link_to "Vuelve a lista de clientes", admin_clientes_path %>
</div>
</div>

app/views/admin/clientes/index.html.erb
<h1 class="text-center p-3">Clientes</h1>



<div class="container" id="clientes">
<%= link_to "Nuevo cliente", new_admin_cliente_path, class: "d-block mb-4" %>
  <% @clientes.each do |cliente| %>
    <a href="<%= admin_cliente_path(cliente) %>" class="d-flex gap-2 align-items-center text-decoration-none text-secondary border border-1 rounded rounded-2 mb-2 p-2">
      <%= render cliente %>
    </a>
  <% end %>
</div>

<div class="d-flex mt-4 m-auto justify-content-center">
<%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/admin/clientes/new.html.erb
<h1 class="text-center m-3">Nuevo cliente</h1>

<div class="container">
<%= render "form", cliente: @cliente %>

<br>

<div>
  <%= link_to "Volver a lista de clientes", admin_clientes_path %>
</div>
</div>

app/views/admin/clientes/show.html.erb
<div class="container m-5 p-3">
  <%= render @cliente %>
  <div>
  <%= link_to "Edita este cliente", edit_admin_cliente_path(@cliente) %> |
  <%= link_to "Volver a lista de clientes", admin_clientes_path %>

  <%= button_to "Borrar este cliente", [:admin, @cliente], method: :delete, class: "mt-2 btn btn-danger" %>
</div>
</div>