config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :disco_pedidos
    resources :pedidos
    resources :canciones
    resources :discos
    resources :artistas
    get "", to: "home#index"
    get 'home/index'
    get 'sesiones/new'
    post 'sesiones/create'
    get 'sesiones/destroy'
    resources :clientes
  end
  get 'carrito', to: "carritos#show", as: "carrito"
  get 'carrito/agregar/:disco_id', to: "carritos#agregar", as: "carrito_agregar"
  get 'carrito/quitar/:disco_id', to: "carritos#quitar", as: "carrito_quitar"
  get 'carrito/menos/:disco_id', to: "carritos#menos", as: "carrito_menos"
  get 'carrito/mas/:disco_id', to: "carritos#mas", as: "carrito_mas"
  get 'carrito/vaciar', to: "carritos#vaciar", as: "carrito_vaciar"
  get "contactanos", to: "home#contactanos"
  get "faq", to: "home#faq"
  get "sobre", to: "home#sobre"
  get "perfil", to: "clientes#perfil"
  get 'sesion', to: "sesiones#new"
  post 'sesion', to: "sesiones#create"
  delete 'sesion', to: "sesiones#destroy"
  get 'home/index'
  get 'home', to: "home#index"
  get 'registro', to: "registros#new"
  post 'registro', to: "registros#create"
  root "home#index"
  get "artistas/buscar"
  get "discos/buscar"
  resources :pedidos, only: %i[ index show new create ]
  resources :canciones, only: %i[ index show ]
  resources :discos, only: %i[ index show ]
  resources :artistas,  only: %i[ index show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/artista.rb
class Artista < ApplicationRecord
    mount_uploader :imagen, ImagenUploader
###
### Associations
###
    has_many :discos
###
### Validations
###
    validates :nombre,  presence: true
    validates :fecha_nacimiento, presence: true
    validates :procedencia, presence: true
end

app/controllers/admin/artistas_controller.rb
class Admin::ArtistasController < ApplicationController
  before_action :set_artista, only: %i[ show edit update destroy ]
  before_action :requiere_ser_admin

  # GET /admin/artistas or /admin/artistas.json
  def index
    @pagy, @artistas = pagy(Artista.all)
  end

  # GET /admin/artistas/1 or /admin/artistas/1.json
  def show
  end

  # GET /admin/artistas/new
  def new
    @artista = Artista.new
  end

  # GET /admin/artistas/1/edit
  def edit
  end

  # POST /admin/artistas or /admin/artistas.json
  def create
    @artista = Artista.new(artista_params)

    respond_to do |format|
      if @artista.save
        format.html { redirect_to admin_artista_url(@artista), notice: "Artista was successfully created." }
        format.json { render :show, status: :created, location: @artista }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artista.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/artistas/1 or /admin/artistas/1.json
  def update
    respond_to do |format|
      if @artista.update(artista_params)
        format.html { redirect_to admin_artista_url(@artista), notice: "El artista ha sido creado." }
        format.json { render :show, status: :ok, location: @artista }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artista.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/artistas/1 or /admin/artistas/1.json
  def destroy
    @artista.discos.each do |disco|
      disco.disco_pedidos.destroy_all
      disco.canciones.destroy_all
      disco.destroy
    end
    @artista.destroy

    respond_to do |format|
      format.html { redirect_to admin_artistas_url, notice: "El artista ha sido borrado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artista
      @artista = Artista.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artista_params
      params.require(:artista).permit(:fecha_nacimiento, :nombre, :procedencia, :imagen)
    end
end

app/controllers/artistas_controller.rb
class ArtistasController < ApplicationController
  before_action :set_artista, only: %i[ show edit update destroy ]

  # GET /artistas or /artistas.json
  def index
    @pagy, @artistas = pagy(Artista.all)
  end

  def buscar
    @pagy, @artistas = pagy(Artista.where("lower(nombre) like lower(?)", "%" + Disco.sanitize_sql_like(params[:q]) + "%"))
    render "index"
  end

  # GET /artistas/1 or /artistas/1.json
  def show
  end

  # GET /artistas/new
  def new
    @artista = Artista.new
  end

  # GET /artistas/1/edit
  def edit
  end

  # POST /artistas or /artistas.json
  def create
    @artista = Artista.new(artista_params)

    respond_to do |format|
      if @artista.save
        format.html { redirect_to artista_url(@artista), notice: "Artista was successfully created." }
        format.json { render :show, status: :created, location: @artista }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artista.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artistas/1 or /artistas/1.json
  def update
    respond_to do |format|
      if @artista.update(artista_params)
        format.html { redirect_to artista_url(@artista), notice: "Artista was successfully updated." }
        format.json { render :show, status: :ok, location: @artista }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artista.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artistas/1 or /artistas/1.json
  def destroy
    @artista.destroy

    respond_to do |format|
      format.html { redirect_to artistas_url, notice: "Artista was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artista
      @artista = Artista.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artista_params
      params.require(:artista).permit(:nombre, :fecha_nacimiento, :procedencia)
    end
end

app/helpers/admin/artistas_helper.rb
module Admin::ArtistasHelper
end

app/helpers/artistas_helper.rb
module ArtistasHelper
end

app/views/artistas/_artista.html.erb
<div id="<%= dom_id artista %>" class="card" >
  <a href="<%= artista_path(artista) %>"><%= image_tag artista.imagen.url, class: "card-img-top" %></a>
  
  <div class="card-body">
    <a data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= artista.nombre %>" class="text-decoration-none link-dark" href="<%= artista_path(artista) %>"><h6 class="card-subtitle text-truncate fs-4 mt-2"><%= artista.nombre %></h6></a>
  </div>

</div>

app/views/artistas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="ms-5">Artistas</h1>
<div class="container my-3 w-75">
  <%= form_with url: artistas_buscar_url, method: :get do |f| %>
  <div class="input-group">
      <%= f.text_field :q, placeholder: "Busca un artista", class: "form-control" %>
      <%= f.submit "Buscar", class: "btn btn-primary" %>
  </div>
  <% end %>
</div>

<div id="discos" class="container m-auto mt-5  ">
    <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-3">
    <% @artistas.each do |artista| %>
    <div class="col">
      <%= render artista %>
    </div>
    <% end %>

    </div>
</div>

<div class="d-flex mt-4 m-auto justify-content-center">
<%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/artistas/show.html.erb
<div class="container mb-5 mt-5 ">
  <div class="row">
    <div class="col-12 col-md-4">
      <%= image_tag @artista.imagen.url, class: "w-100" %>
    </div>
    <div class="col-12 col-md-8">
      <div class="ms-4 mt-2">
        <h2 class=""><%= @artista.nombre %></h2>
      </div>
      <div class="mt-4 ms-4">
        <span class="badge bg-info fs-6" ><%= @artista.fecha_nacimiento.year %></span>
        <span class="badge bg-danger fs-6" ><%= @artista.procedencia %></span>
      </div>
      
      <div class=" ms-4 mt-4">
        <ul class="list-group">
          <% @artista.discos.each do |disco| %>
            <a href="<%= disco_path(disco) %>" class="list-group-item d-flex align-items-center justify-content-between">
              
              <span><%= image_tag disco.portada.url, size: "50x50" %><span class="ms-2"><%= disco.nombre %></span></span>
              
              <span><%= disco.fecha_lanzamiento.year %></span>
            </a>
          <% end %>
        </ul>
      </div>
      
    </div>

  </div>
</div>