config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :disco_pedidos
    resources :pedidos
    resources :canciones
    resources :discos
    resources :artistas
    get "", to: "home#index"
    get 'home/index'
    get 'sesiones/new'
    post 'sesiones/create'
    get 'sesiones/destroy'
    resources :clientes
  end
  get 'carrito', to: "carritos#show", as: "carrito"
  get 'carrito/agregar/:disco_id', to: "carritos#agregar", as: "carrito_agregar"
  get 'carrito/quitar/:disco_id', to: "carritos#quitar", as: "carrito_quitar"
  get 'carrito/menos/:disco_id', to: "carritos#menos", as: "carrito_menos"
  get 'carrito/mas/:disco_id', to: "carritos#mas", as: "carrito_mas"
  get 'carrito/vaciar', to: "carritos#vaciar", as: "carrito_vaciar"
  get "contactanos", to: "home#contactanos"
  get "faq", to: "home#faq"
  get "sobre", to: "home#sobre"
  get "perfil", to: "clientes#perfil"
  get 'sesion', to: "sesiones#new"
  post 'sesion', to: "sesiones#create"
  delete 'sesion', to: "sesiones#destroy"
  get 'home/index'
  get 'home', to: "home#index"
  get 'registro', to: "registros#new"
  post 'registro', to: "registros#create"
  root "home#index"
  get "artistas/buscar"
  get "discos/buscar"
  resources :pedidos, only: %i[ index show new create ]
  resources :canciones, only: %i[ index show ]
  resources :discos, only: %i[ index show ]
  resources :artistas,  only: %i[ index show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/disco.rb
class Disco < ApplicationRecord

  mount_uploader :portada, PortadaUploader
  
###
### Associations
###  
  belongs_to :artista
  has_many :canciones
  has_many :disco_pedidos

###
### Validations
###
  validates :genero, presence: true
  validates :precio, numericality: { greater_than_or_equal_to: 0.0, less_than: 1000.0}
  validates :nombre, presence: true
end

app/controllers/admin/discos_controller.rb
class Admin::DiscosController < ApplicationController
  before_action :set_disco, only: %i[ show edit update destroy ]
  before_action :requiere_ser_admin
  # GET /admin/discos or /admin/discos.json
  def index
    @pagy, @discos = pagy(Disco.all)
  end

  # GET /admin/discos/1 or /admin/discos/1.json
  def show
  end

  # GET /admin/discos/new
  def new
    @disco = Disco.new
  end

  # GET /admin/discos/1/edit
  def edit
  end

  # POST /admin/discos or /admin/discos.json
  def create
    @disco = Disco.new(disco_params)

    respond_to do |format|
      if @disco.save
        format.html { redirect_to admin_disco_url(@disco), notice: "Disco ha sido creado." }
        format.json { render :show, status: :created, location: @disco }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @disco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/discos/1 or /admin/discos/1.json
  def update
    respond_to do |format|
      if @disco.update(disco_params)
        format.html { redirect_to admin_disco_url(@disco), notice: "Disco ha sido actualizado." }
        format.json { render :show, status: :ok, location: @disco }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @disco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/discos/1 or /admin/discos/1.json
  def destroy
    @disco.disco_pedidos.destroy_all
    @disco.canciones.destroy_all
    @disco.destroy

    respond_to do |format|
      format.html { redirect_to admin_discos_url, notice: "Disco ha sido borrado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disco
      @disco = Disco.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def disco_params
      params.require(:disco).permit(:artista_id, :nombre, :descripcion, :fecha_lanzamiento, :precio, :genero, :portada)
    end
end

app/controllers/discos_controller.rb
class DiscosController < ApplicationController
  before_action :set_disco, only: %i[ show edit update destroy ]

  # GET /discos or /discos.json
  def index
    @pagy, @discos = pagy(Disco.all)
    
  end

  def buscar
    @pagy, @discos = pagy(Disco.where("lower(nombre) like lower(?)", "%" + Disco.sanitize_sql_like(params[:q]) + "%"))
    render "index"
  end

  # GET /discos/1 or /discos/1.json
  def show
  end

  # GET /discos/new
  def new
    @disco = Disco.new
  end

  # GET /discos/1/edit
  def edit
  end

  # POST /discos or /discos.json
  def create
    @disco = Disco.new(disco_params)

    respond_to do |format|
      if @disco.save
        format.html { redirect_to disco_url(@disco), notice: "Disco was successfully created." }
        format.json { render :show, status: :created, location: @disco }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @disco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discos/1 or /discos/1.json
  def update
    respond_to do |format|
      if @disco.update(disco_params)
        format.html { redirect_to disco_url(@disco), notice: "Disco was successfully updated." }
        format.json { render :show, status: :ok, location: @disco }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @disco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discos/1 or /discos/1.json
  def destroy
    @disco.destroy

    respond_to do |format|
      format.html { redirect_to discos_url, notice: "Disco was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disco
      @disco = Disco.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def disco_params
      params.require(:disco).permit(:nombre, :artista_id, :descripcion, :genero, :precio)
    end
end

app/helpers/admin/discos_helper.rb
module Admin::DiscosHelper
end

app/helpers/discos_helper.rb
module DiscosHelper

    def minutos_segundos(segundos)
        "%d:%02d" % [segundos / 60, segundos % 60]
    end
end

app/views/admin/discos/_disco.html.erb
    <p>Id: <%= disco.id %></p>
    <p>Nombre: <%= disco.nombre %></p>
    <p>Artista: <%= disco.artista.nombre %></p>
    <p>Género: <%= disco.genero %></p>
    <p>Precio: <%= disco.precio %></p>
    <p>Fecha lanzamiento: <%= disco.fecha_lanzamiento %></p>
    <% if muestra_descripcion %>
      <p>Descripción: <%= disco.descripcion %></p>
      <%= image_tag disco.portada.url, size: "200x200" %>
    <% end %>

app/views/admin/discos/_form.html.erb
<%= form_with(model: [:admin, disco]) do |form| %>
  <% if disco.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(disco.errors.count, "error") %> prohibited this disco from being saved:</h2>

      <ul>
        <% disco.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mt-2">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>
   <div class="mt-2">
    <%= form.label :artista_id %>
    <%= form.text_field :artista_id %>
  </div>
   <div class="mt-2">
    <%= form.label :genero %>
    <%= form.text_field :genero %>
  </div>
  <div class="mt-2">
    <%= form.label :precio %>
    <%= form.number_field :precio %>
  </div>
  <div class="mt-2">
    <%= form.label :fecha_lanzamiento %>
    <%= form.date_field :fecha_lanzamiento %>
  </div>
  <div class="mt-2">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>
  <div class="mt-2">
    <%= form.label :portada %>
    <%= form.file_field :portada %>
  </div>
  <div class="mt-2">
    <%= image_tag disco.portada.url, size: "200x200" %>
  </div>
  <div class="mt-2">
    <%= form.submit class: "btn btn-success mt-2" %>
  </div>
<% end %>

app/views/admin/discos/edit.html.erb
<h1 class="text-center m-3">Editar disco</h1>

<div class="container">
<%= render "form", disco: @disco %>

<br>

<div>
  <%= link_to "Muestra este disco", [:admin, @disco] %> |
  <%= link_to "Vuelve a lista de discos", admin_discos_path %>
</div>
</div>

app/views/admin/discos/index.html.erb
<h1 class="text-center p-3">Discos</h1>



<div class="container" id="discos">
<%= link_to "Nuevo disco", new_admin_disco_path, class: "d-block mb-4" %>
  <% @discos.each do |disco| %>
    <a href="<%= admin_disco_path(disco) %>" class="d-flex gap-2 align-items-center text-decoration-none text-secondary border border-1 rounded rounded-2 mb-2 p-2">
      <%= render disco, muestra_descripcion: false %>
    </a>
  <% end %>
</div>

<div class="d-flex mt-4 m-auto justify-content-center">
<%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/admin/discos/new.html.erb
<h1 class="text-center m-3">Nuevo disco</h1>

<div class="container">
<%= render "form", disco: @disco %>

<br>

<div>
  <%= link_to "Volver a lista de discos", admin_discos_path %>
</div>
</div>

app/views/admin/discos/show.html.erb
<div class="container m-5 p-3">
  <%= render @disco, muestra_descripcion: true %>
  <div>
  <%= link_to "Edita este disco", edit_admin_disco_path(@disco) %> |
  <%= link_to "Volver a lista de discos", admin_discos_path %>

  <%= button_to "Borrar este disco", [:admin, @disco], method: :delete, class: "mt-2 btn btn-danger" %>
</div>
</div>